CompileFlags:
  Add: [-xc, -std=c23, -Wall, -Wextra, -Wpedantic, -Wno-empty-translation-unit]
  # -Wpedantic causes false positive
  # warning: ISO C requires a translation unit to contain at least one declaration
  # -Wno-empty-translation-unit turns that off
