# https://rust-lang.github.io/rustfmt/?version=v1.7.0&search=
max_width = 110
use_small_heuristics = "Max"
struct_field_align_threshold = 16
enum_discrim_align_threshold = 16
group_imports = "StdExternalCrate"
reorder_impl_items = true
imports_granularity = "Crate"
match_block_trailing_comma = true
# hard_tabs = true # Use tab characters for indentation, spaces for alignment
format_strings = true
fn_single_line = true
condense_wildcard_suffixes = true
