theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
# gutters = []
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
cursorline = true
# cursorcolumn = true
rulers = [80]

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
tab = ">"
tabpad = " "
